spring:
  security:
    oauth2:
      client:

        provider:
          # Register google provider
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://accounts.google.com/o/oauth2/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

          # Register github provider
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id

          # Register facebook provider
          facebook:
            authorization-uri: https://www.facebook.com/v2.8/dialog/oauth
            token-uri: https://graph.facebook.com/v2.8/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email
            user-name-attribute: id

          # Register CodeAdvisor provider
          web-app:
            issuer-uri: http://127.0.0.1:9090
            authorization-uri: http://127.0.0.1:9090/oauth2/authorize
            token-uri: http://127.0.0.1:9090/oauth2/token



        registration:
          # Register google Service
          google:
           provider: google
           client-id: 365243546348-q5tsb7lho4g0jgrl1fmrr9rqrfatin9s.apps.googleusercontent.com
           client-secret: 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
           redirect-uri: http://localhost:8080/login/oauth2/code/google
           scope:
             - email
             - profile
             - openid
           authorization-grant-type:
             - authorization_code
           client-authentication-method:
             - client_secret_post
             - client_secret_basic
           client-name: google

          # Register Github Service
          github:
            client-id: Ov23liYrbQZwRW0nX3fU
            client-secret: ce45a4670c41374de8099964137565a5fbf205b3
            redirect-uri: http://localhost:8080/login/oauth2/code/github
            scope:
              - read:user
            authorization-grant-type:
              - authorization_code
            client-authentication-method:
              - client_secret_post
              - client_secret_basic
            client-name: github

          # Register Facebook Service
          facebook:
            client-id: 1840988583327351
            client-secret: 95a02ce4d11a2f9ef00b7247a99cc81d
            redirect-uri: http://localhost:8080/login/oauth2/code/facebook
            scope:
              - public_profile
              - email
            authorization-grant-type:
              - authorization_code
            client-authentication-method:
              - client_secret_post
              - client_secret_basic
            client-name: facebook

          # Register CodeAdvisor Service
          web-app:
            provider: web-app
            client-id: web-app
            client-secret: webapp
            redirect-uri: http://127.0.0.1:8168/login/oauth2/code/web-app
            scope:
              - openid
              - profile
              - email
            authorization-grant-type:
              - authorization_code
            client-authentication-method:
              - client_secret_post
              - client_secret_basic
            client-name: web-app

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Request-Headers
        - SaveSession
      routes:
        - id: identity # Register Identity Service
          uri: http://127.0.0.1:9090
          predicates:
            - Path=/identity/**
          filters:
            - TokenRelay=
            - RewritePath=/identity/(?<segment>.*),/$\{segment}

        - id: user-service
          uri: http://127.0.0.1:8085
          predicates:
            - Path=/users/**
          filters:
            - TokenRelay=
            - RewritePath=/users/(?<segment>.*),/$\{segment}

        - id: codeAdvisor-ui # Register Frontend (NextJS)
          uri: http://127.0.0.1:3000
          predicates:
            - Path=/**
          filters:
            - TokenRelay=

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

server:
  port: 8168

client-security-matchers: >
  /login/**,
  /oauth2/**,
  /logout/**,
  /en/**,
  /auth/**,
  /business/**,
  /profile/**,
  /contents/**,
  /users/**,
  /media/**,
  /identity/**

client-permit-matchers: >
  /contents/**,
  /media/**,
  /users/**,
  /login/**,
  /oauth2/**,
  /en/**,
  /auth/**,
  /contactSupport/**,
  /error/**,
  /actuator/**,
  /info/**,
  /health/**,
  /prometheus/**,
  /business/**,
  /profile/**,
  /identity/**